-- CreateTable
CREATE TABLE `test` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
    `test` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
